

docker run -d -ti --name "ubuntu" -v "%cd%":/app --entrypoint /bin/bash my-ubuntu
./client -email "gw.christophe28@gmail.com" -character "Larius Logsalot" -password "letmein199" -mapid 148 -maptype 3 -l ../log.txt ./libkamadan_trade_chat.so
./client -email "gw.logaine@gmail.com" -character "Logaine Loggington" -password "letmein877" -mapid 148 -maptype 3 -l ../log.txt ./libkamadan_trade_chat.so

antoniolopesp@gmail.com