ENV["VAGRANT_DISABLE_RESOLV_REPLACE"] = "1"
ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin" if RUBY_PLATFORM.include? "mingw"		# Fix folder structure for Cygwin installations
ENV["VAGRANT_DEFAULT_PROVIDER"] = "virtualbox"		# Use VirtualBox by default.
ENV["VAGRANT_PREFER_SYSTEM_BIN"] = "0"				# Avoid conflicting versions of SSH with cygwin etc
ENV["VAGRANT_USE_VAGRANT_TRIGGERS"] = "1"			#
ENV["VAGRANT_PREFER_SYSTEM_BIN"] = "1"
				
Vagrant.require_version ">= 2.1.0"	# 2.1.0 required for vagrant triggers.
$config_folder = "#{File.dirname(__FILE__)}/VagrantConfig"		# Folder where all required files are, escaping any spaces. Make sure this exists!!
$rsync_folder_excludes = {		# Any folders that you don't want to rsync to the server.
	"." => "/vagrant"
}

# ------------------	Vagrant Pre-Includes	------------------ #
# Functions and Project variables.
# ---------------------------------------------------------------- #
pre_includes = [
	"#{$config_folder}/Project.rb",		#	Identifiers for this project e.g. repo location, costcentre
	"#{$config_folder}/Functions.rb",	# 	Helper functions
	"#{$config_folder}/Plugins.rb"		#	Automatically installs plugins required for this vagrant installation.
]
pre_includes.each do |filename|
	require filename # unless not File.exists?(filename)
end

$rsync_excludes = $rsync_excludes | [
'Dependencies/Headquarter/bin/',
'Dependencies/Headquarter/.vs/',
'hq_client/.vs/',
'hq_client/x64/',
'hq_client/x86/',
'hq_client/win32build/',
'hq_client/linuxbuild/'];

enforce_machine_name_requirement()

Ubuntu20_Official_amd64 = {
  'box_url' => 'https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-vagrant.box',
  'box_name' => 'ubuntu-20.04_amd64_official'
}

Ubuntu18_Official_amd64 = {
  'box_url' => 'https://cloud-images.ubuntu.com/bionic/20200206/bionic-server-cloudimg-amd64-vagrant.box',
  'box_name' => 'ubuntu-18.04_amd64_official'
}

Ubuntu_Official_i386 = {
	'box_url' => 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box',
	'box_name' => 'ubuntu-14.04_i386_official'
}
Ubuntu_Official_amd64 = {
	'box_url' => 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box',
	'box_name' => 'ubuntu-14.04_amd64_official'
}
Debian8_Official_amd64 = {
	'box_url' => 'https://github.com/holms/vagrant-jessie-box/releases/download/Jessie-v0.1/Debian-jessie-amd64-netboot.box',
	'box_name' => 'debian-8_amd64_official'
}
# Choose 1 of the above boxes for our local environment. 
# Try swapping out for i386 version if your PC is a million years old and doesn't support VT-x.

VirtualBox = Ubuntu20_Official_amd64

# ------------------    Definitions		 ------------------
if File.file?("#{File.dirname(__FILE__)}/.env.rb") then
  require "#{File.dirname(__FILE__)}/.env.rb"
end

server_config = {
	'is_local'=>0,
	'is_production'=>0,
	'is_cloud'=>0,
	'is_aws'=>0,
	'is_google'=>0,
	'is_azure'=>0,
	'is_rackspace'=>0,
	'is_linode'=>0,
	'deployment_date'=>Time.now.strftime("%Y%m%d%H%M%S"),
  'repository_code_folder'=>'/home/vagrant/kamadan-trade-client',
  'db_user'=>'nodejs',
  'db_host'=>'127.0.0.1',
  'db_schema'=>'kamadan',
  'db_pass'=>ENV["DB_PASS"] || 'K4maDan1423-zseq',
  'google_drive_backups_folder_id' => '1ZzNLnWUmj3SbyoI3zc2MJBjRifLWGzpP',
  'google_apis_private_key' => ENV["google_apis_private_key"],
  'google_apis_client_email' => ENV["google_apis_client_email"],
  'gw_kamadan_login' => {
    'email'=>'3vangelist@snow-guild.com',
    'password'=>'D3miaFr3lluis',
    'character'=>'Failing Blowtorch'
  },
  'gw_ascalon_login' => {
    'email'=>'jondxms@googlemail.com',
    'password'=>'B4c4Rd189',
    'character'=>'Grunk Logsmash'
  }
}

local_config = Marshal::load(Marshal.dump(server_config))
local_config['is_local'] = 1

cloud_config = Marshal::load(Marshal.dump(server_config))
cloud_config['is_cloud'] = 1

production_config = Marshal::load(Marshal.dump(cloud_config))
production_config['is_production'] = 1

# ------------------ 	Vagrant Machine Definitions		 ------------------

Machines = {
	'VirtualBox' => {
		'lodcal' => {
			'hostnames' => ['local.kamadanclient.com'],	# With virtualbox, the first item is added to hosts file, then removed for further processing (see VagrantConfig/Functions.rb)
			'server_config' => local_config.merge({
        'disable_client'=>true
      }),
			'ip_address' => '10.10.10.52',
      'deployment_script'=>{
        'path' => 'deploy.sh',
        'args' => [server_config['db_user'], server_config['db_pass'], server_config['db_schema']]
      },
			'code_to_provision' => 'local'
		}
	},
  'ManagedServers' => {
    'local' => {
      'ip_address' => '10.10.10.51',
			'server_config' => cloud_config.merge({
				'repository_code_folder'=>'/home/vagrant/kamadan-trade-client',
        'gw_kamadan_login' => {
          'email'=>'3vangelist@snow-guild.com',
          'password'=>'D3miaFr3lluis',
          'character'=>'Failing Blowtorch'
        },
        'gw_ascalon_login' => {
          'email'=>'',#'jondxms@googlemail.com',
          'password'=>'B4c4Rd189',
          'character'=>'Grunk Logsmash'
        }
			}),
			'code_to_provision' => 'local',
			'deployment_script'=>'deploy.sh',
			'prompt_user_before_provision' => 0,
			'os' => 'linux'
    },
		'ramnode' => {
			'ip_address' => '107.191.98.41',
			'server_config' => cloud_config.merge({
				'repository_code_folder'=>'/home/ubuntu/kamadan-trade-client',
        'gw_kamadan_login' => {
          # 'email'=>'3vangelist@snow-guild.com',
          # 'password'=>'B4c4Rd189',
          # 'character'=>'Failing Blowtorch'
          'email'=>'trade@snow-guild.com',
          'password'=>'k4MaDAN771!',
          'character'=>'Lorraine Logsalot'
        },
        'gw_ascalon_login' => {
          # 'email'=>'jondxms@googlemail.com',
          # 'password'=>'B4c4Rd189',
          # 'character'=>'Grunk Logsmash'
          'email'=>'gw.christophe28@gmail.com',
          'password'=>'letmein199',
          'character'=>'Larius Logsalot'
        },
        'is_cloud'=>1,
        'ssl_email'=>'jon@3vcloud.uk',
        'ssl_domains' => ['kamadan.gwtoolbox.com','ascalon.gwtoolbox.com']
			}),
			'code_to_provision' => 'local',
			#'rsync_path' => '~/local/bin/rsync',	# Custom rsync binary on server.
			'deployment_script'=>'deploy.sh',
			'prompt_user_before_provision' => 0,
			'ssh_username' => 'root',
			'os' => 'linux'
		}
	}
}

Vagrant.configure("2") do |config|
	Machines['VirtualBox'].each do |machine_name,machine_properties|
		config.vm.define machine_name do |machine|
			machine.vm.box = VirtualBox['box_name']
			machine.vm.box_url = VirtualBox['box_url'] || nil
      machine.vbguest.auto_update = false
			local_machine_setup(machine,machine_name,machine_properties);
		end
		config.vm.provider :virtualbox do |v, override|
			#v.gui=true
			v.customize ['modifyvm', :id, '--memory', machine_properties['server_memory_size'] || VirtualBox['server_memory_size'] || '1024']
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
	end
end

# ------------------	Vagrant Post-Includes	------------------ #
# Provider specific details and VM provider setups.
# ---------------------------------------------------------------- #
post_includes = [
	"#{$config_folder}/CloudProviderSetup.rb"
]
post_includes.each do |filename|
	require filename # unless not File.exists?(filename)
end